#include "encoder.h" //Biblioteca de funções para controle do encoder rotativo
#include "main.h"  //Arquivo gerado pelo STM32CubeIDE que contém as definições e protótipos das funções de inicialização dos periféricos, como timers e GPIOs. Também inclui a definição da variável htim2, que é usada para ler o encoder rotativo.

#define ENCODER_STEP 4 // Define o número de pulsos do encoder rotativo que correspondem a um passo de rotação. Esse valor é usado para determinar a direção de rotação do encoder, comparando a diferença entre o valor atual do contador do timer e o valor anterior (old_count). Se a diferença for maior ou igual a ENCODER_STEP, significa que houve uma rotação no sentido horário (ENC_CW). Se a diferença for menor ou igual a -ENCODER_STEP, significa que houve uma rotação no sentido anti-horário (ENC_CCW). O valor de 4 é comumente usado para encoders rotativos com 20 pulsos por revolução, onde cada passo corresponde a 4 pulsos (20 pulsos / 4 passos = 5 passos por revolução).
#define DEBOUNCE_BUTTON 400

extern TIM_HandleTypeDef htim2; // Declaração da variável htim2, que é definida no arquivo main.c e usada para ler o encoder rotativo. Essa variável é do tipo TIM_HandleTypeDef, que é uma estrutura definida na biblioteca HAL do STM32 para representar um timer e suas configurações. O timer htim2 deve ser configurado no modo Encoder Interface para que seja possível ler os pulsos gerados pelo encoder rotativo e determinar a direção de rotação.

static volatile uint16_t old_count = 0; // Variável estática para armazenar o valor anterior do contador do timer. Essa variável é usada para calcular a diferença entre o valor atual do contador e o valor anterior, o que permite determinar a direção de rotação do encoder rotativo (horário ou anti-horário). O tipo int16_t é usado para garantir que a variável possa armazenar valores negativos, caso o contador do timer seja configurado para contar em ambos os sentidos (up/down).

/*------------------------------------------------------------------
 * Inicialização
 *-----------------------------------------------------------------*/
void encoder_init(void)
{
    HAL_TIM_Encoder_Start(&htim2, TIM_CHANNEL_ALL); // Inicia o timer htim2 no modo Encoder Interface para ler os pulsos do encoder rotativo. A função HAL_TIM_Encoder_Start é uma função da biblioteca HAL do STM32 que configura o timer para operar no modo Encoder Interface e começa a contagem dos pulsos gerados pelo encoder. O parâmetro TIM_CHANNEL_ALL indica que ambos os canais do timer (canal 1 e canal 2) serão usados para ler os sinais do encoder, o que é necessário para determinar a direção de rotação.

    old_count = (uint16_t)__HAL_TIM_GET_COUNTER(&htim2); // Lê o valor inicial do contador do timer htim2 e armazena na variável old_count. A função __HAL_TIM_GET_COUNTER é uma macro da biblioteca HAL do STM32 que retorna o valor atual do contador do timer. O valor é convertido para int16_t para garantir que a variável old_count possa armazenar valores negativos, caso o contador do timer seja configurado para contar em ambos os sentidos (up/down). Essa leitura inicial é importante para que a função encoder_get_event possa calcular corretamente a diferença entre o valor atual do contador e o valor anterior, permitindo determinar a direção de rotação do encoder rotativo.
}

/*------------------------------------------------------------------
 * Retorna evento do encoder
 *-----------------------------------------------------------------*/

EncoderEvent_t encoder_get_event(void) // Função para ler o estado do encoder rotativo e retornar um evento correspondente. Essa função verifica a diferença entre o valor atual do contador do timer e o valor anterior (old_count) para determinar a direção de rotação do encoder (horário ou anti-horário). Além disso, a função também verifica se o botão do encoder foi pressionado, usando a função HAL_GPIO_ReadPin para ler o estado do pino correspondente ao botão. Se o botão for pressionado, a função retorna um evento de pressão (ENC_PRESS). Caso contrário, se houver uma rotação no sentido horário, retorna ENC_CW, e se houver uma rotação no sentido anti-horário, retorna ENC_CCW. Se não houver nenhum evento, retorna ENC_NONE.
{
    uint16_t new_count; // Variável para armazenar o valor atual do contador do timer. Essa variável é usada para calcular a diferença entre o valor atual do contador e o valor anterior (old_count), o que permite determinar a direção de rotação do encoder rotativo (horário ou anti-horário). O tipo int16_t é usado para garantir que a variável possa armazenar valores negativos, caso o contador do timer seja configurado para contar em ambos os sentidos (up/down).
    int16_t delta; // Variável para armazenar a diferença entre o valor atual do contador (new_count) e o valor anterior (old_count). Essa variável é usada para determinar a direção de rotação do encoder rotativo. Se delta for positivo e maior ou igual a 4, significa que houve uma rotação no sentido horário (ENC_CW). Se delta for negativo e menor ou igual a -4, significa que houve uma rotação no sentido anti-horário (ENC_CCW). O valor de 4 é usado como um limiar para evitar ruídos ou pequenas variações no contador que podem ocorrer devido a vibrações ou imperfeições no encoder.

    static uint32_t last_button_tick = 0; // Variável estática para armazenar o último tempo em que o botão do encoder foi pressionado. Essa variável é usada para implementar um debounce no botão, evitando que múltiplos eventos de pressão sejam registrados em um curto período de tempo devido a ruídos ou vibrações. A função HAL_GetTick é usada para obter o tempo atual em milissegundos desde o início do programa, e a diferença entre o tempo atual e last_button_tick é verificada para garantir que pelo menos 200 milissegundos tenham se passado desde a última pressão registrada antes de retornar um novo evento de pressão (ENC_PRESS).

    new_count = (uint16_t)__HAL_TIM_GET_COUNTER(&htim2); // Lê o valor atual do contador do timer htim2 e armazena na variável new_count. A função __HAL_TIM_GET_COUNTER é uma macro da biblioteca HAL do STM32 que retorna o valor atual do contador do timer. O valor é convertido para int16_t para garantir que a variável new_count possa armazenar valores negativos, caso o contador do timer seja configurado para contar em ambos os sentidos (up/down). Essa leitura é necessária para calcular a diferença entre o valor atual do contador e o valor anterior (old_count), permitindo determinar a direção de rotação do encoder rotativo.

    delta = (int16_t)(new_count - old_count); // Calcula a diferença entre o valor atual do contador (new_count) e o valor anterior (old_count) e armazena na variável delta. Essa diferença é usada para determinar a direção de rotação do encoder rotativo. Se delta for positivo e maior ou igual a 4, significa que houve uma rotação no sentido horário (ENC_CW). Se delta for negativo e menor ou igual a -4, significa que houve uma rotação no sentido anti-horário (ENC_CCW). O valor de 4 é usado como um limiar para evitar ruídos ou pequenas variações no contador que podem ocorrer devido a vibrações ou imperfeições no encoder.

    if(delta >= ENCODER_STEP) // Verifica se a diferença delta é maior ou igual a 4, o que indica uma rotação no sentido horário do encoder rotativo. Se essa condição for verdadeira, a função retorna o evento ENC_CW (Clockwise) para indicar que o encoder foi girado no sentido horário. Antes de retornar o evento, a variável old_count é atualizada com o valor de new_count para que a próxima leitura do contador possa calcular corretamente a diferença e determinar a direção de rotação.
    {
        old_count = new_count; // Atualiza a variável old_count com o valor atual do contador (new_count) para que a próxima leitura do contador possa calcular corretamente a diferença e determinar a direção de rotação do encoder rotativo. Essa atualização é importante para garantir que a função encoder_get_event possa detectar corretamente as próximas rotações do encoder, comparando o valor atual do contador com o valor anterior armazenado em old_count.
        return ENC_CW; // Retorna o evento ENC_CW (Clockwise) para indicar que o encoder foi girado no sentido horário. Esse evento pode ser usado pela máquina de estados ou pela lógica de controle da aplicação para executar ações específicas quando o encoder for girado no sentido horário, como navegar para baixo em um menu ou aumentar um valor configurável.
    }

    if(delta <= -ENCODER_STEP) // Verifica se a diferença delta é menor ou igual a -4, o que indica uma rotação no sentido anti-horário do encoder rotativo. Se essa condição for verdadeira, a função retorna o evento ENC_CCW (Counter-Clockwise) para indicar que o encoder foi girado no sentido anti-horário. Antes de retornar o evento, a variável old_count é atualizada com o valor de new_count para que a próxima leitura do contador possa calcular corretamente a diferença e determinar a direção de rotação.
    {
        old_count = new_count; // Atualiza a variável old_count com o valor atual do contador (new_count) para que a próxima leitura do contador possa calcular corretamente a diferença e determinar a direção de rotação do encoder rotativo. Essa atualização é importante para garantir que a função encoder_get_event possa detectar corretamente as próximas rotações do encoder, comparando o valor atual do contador com o valor anterior armazenado em old_count.
        return ENC_CCW; // Retorna o evento ENC_CCW (Counter-Clockwise) para indicar que o encoder foi girado no sentido anti-horário. Esse evento pode ser usado pela máquina de estados ou pela lógica de controle da aplicação para executar ações específicas quando o encoder for girado no sentido anti-horário, como navegar para cima em um menu ou diminuir um valor configurável.
    }

    /* Botão pressionado */
    if(HAL_GPIO_ReadPin(ENC_SW_GPIO_Port, ENC_SW_Pin) == GPIO_PIN_RESET) // Verifica se o botão do encoder foi pressionado, lendo o estado do pino correspondente ao botão usando a função HAL_GPIO_ReadPin. Se o estado do pino for GPIO_PIN_RESET, significa que o botão foi pressionado (considerando que o botão está configurado com um pull-up, onde o estado normal é GPIO_PIN_SET e o estado pressionado é GPIO_PIN_RESET). Se essa condição for verdadeira, a função retorna um evento de pressão (ENC_PRESS) para indicar que o botão do encoder foi pressionado. Antes de retornar o evento, a função também implementa um debounce verificando se pelo menos 200 milissegundos se passaram desde a última pressão registrada, usando a variável last_button_tick para armazenar o tempo da última pressão e a função HAL_GetTick para obter o tempo atual em milissegundos.
    {
        uint32_t now = HAL_GetTick(); // Obtém o tempo atual em milissegundos desde o início do programa usando a função HAL_GetTick. Esse valor é usado para implementar um debounce no botão do encoder, garantindo que múltiplos eventos de pressão não sejam registrados em um curto período de tempo devido a ruídos ou vibrações. A variável last_button_tick armazena o tempo da última pressão registrada, e a diferença entre o tempo atual (now) e last_button_tick é verificada para garantir que pelo menos 200 milissegundos tenham se passado antes de retornar um novo evento de pressão (ENC_PRESS).

        if((now - last_button_tick) > DEBOUNCE_BUTTON) // Verifica se a diferença entre o tempo atual (now) e o tempo da última pressão registrada (last_button_tick) é maior que 200 milissegundos. Essa verificação é usada para implementar um debounce no botão do encoder, garantindo que múltiplos eventos de pressão não sejam registrados em um curto período de tempo devido a ruídos ou vibrações. Se essa condição for verdadeira, significa que o botão foi pressionado e o debounce foi bem-sucedido, permitindo que a função retorne um evento de pressão (ENC_PRESS) para indicar que o botão do encoder foi pressionado.
        {
            last_button_tick = now; // Atualiza a variável last_button_tick com o tempo atual (now) para registrar o momento da última pressão do botão. Essa atualização é importante para garantir que a próxima vez que o botão for pressionado, a função encoder_get_event possa verificar corretamente se pelo menos 200 milissegundos se passaram desde a última pressão registrada, implementando assim o debounce e evitando múltiplos eventos de pressão causados por ruídos ou vibrações.
            return ENC_PRESS; // Retorna o evento ENC_PRESS para indicar que o botão do encoder foi pressionado. Esse evento pode ser usado pela máquina de estados ou pela lógica de controle da aplicação para executar ações específicas quando o botão do encoder for pressionado, como selecionar uma opção em um menu ou confirmar uma configuração.
        }
    }

    return ENC_NONE; // Retorna o evento ENC_NONE para indicar que não houve nenhum evento de rotação ou pressão do encoder. Esse valor pode ser usado pela máquina de estados ou pela lógica de controle da aplicação para indicar que o estado do encoder não mudou desde a última leitura, permitindo que a aplicação continue aguardando por eventos futuros sem executar ações desnecessárias.
}
